include(InstallRequiredSystemLibraries)

set(CPACK_PACKAGE_NAME "solver")

set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "1")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_PACKAGE_VERSION_TWEAK "0")

set(CPACK_PACKAGE_CONTACT "boban4@example.com")

set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Solver application")

set(CPACK_PACKAGE_DESCRIPTION_FILE ${CMAKE_CURRENT_SOURCE_DIR}/DESCRIPTION)

set(CPACK_RESOURCE_FILE_LICENSE ${CMAKE_CURRENT_SOURCE_DIR}/LICENSE)

set(CPACK_GENERATOR "DEB;RPM;ZIP;TGZ")

include(CPack)
