include(InstallRequiredSystemLibraries)

set(CPACK_PACKAGE_NAME "solver")

set(CPACK_PACKAGE_VERSION_MAJOR ${PRINT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PRINT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PRINT_VERSION_PATCH})
set(CPACK_PACKAGE_VERSION_TWEAK ${PRINT_VERSION_TWEAK})

set(CPACK_PACKAGE_CONTACT "boban4@example.com")

set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Solver application")

set(CPACK_PACKAGE_DESCRIPTION_FILE ${CMAKE_CURRENT_SOURCE_DIR}/DESCRIPTION)

set(CPACK_RESOURCE_FILE_LICENSE ${CMAKE_CURRENT_SOURCE_DIR}/LICENSE)

set(CPACK_GENERATOR "ZIP;TGZ")

include(CPack)
